name: zjai_com
channels:
- defaults
dependencies:
- backports=1.0=py35_0
- backports.weakref=1.0rc1=py35_0
- bleach=1.5.0=py35_0
- certifi=2016.2.28=py35_0
- cudatoolkit=8.0=3
- cudnn=6.0.21=cuda8.0_0
- html5lib=0.9999999=py35_0
- libgcc=5.2.0=0
- libprotobuf=3.4.0=0
- markdown=2.6.9=py35_0
- mkl=2017.0.3=0
- numpy=1.13.1=py35_0
- openssl=1.0.2l=0
- pip=9.0.1=py35_1
- protobuf=3.4.0=py35_0
- python=3.5.4=0
- readline=6.2=2
- setuptools=36.4.0=py35_1
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tensorflow-gpu=1.3.0=0
- tensorflow-gpu-base=1.3.0=py35cuda8.0cudnn6.0_1
- tensorflow-tensorboard=0.1.5=py35_0
- tk=8.5.18=0
- werkzeug=0.12.2=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - absl-py==0.2.0
  - aniso8601==3.0.0
  - chardet==3.0.4
  - click==6.7
  - cython==0.28.2
  - flask==1.0.2
  - flask-restplus==0.10.1
  - gunicorn==19.8.1
  - h5py==2.7.1
  - idna==2.6
  - itsdangerous==0.24
  - jinja2==2.10
  - jsonschema==2.6.0
  - keras==2.1.6
  - keras-resnet==0.1.0
  - lxml==4.2.1
  - markupsafe==1.0
  - opencv-python==3.4.0.12
  - pillow==5.1.0
  - pytz==2018.4
  - pyyaml==3.12
  - requests==2.18.4
  - scipy==1.1.0
  - tensorflow==1.5.0
  - urllib3==1.22